#!/bin/sh

USER=$(id -un)
UID=$(id -u)
GID=$(id -g)
BUILDER_TAG=aosp-${USER}:v0.0.2
DOCKER_NAME=$(id -un)

if [ "$1" = "docker" ]
then
	docker build --build-arg uid=${UID} --build-arg gid=${GID} -t ${BUILDER_TAG} docker
elif [ "$1" = "aosp" ]
then

	if [ ! -d "./user" ]
	then
		mkdir user
	fi	
	
	cp ~/.gitconfig ./user/.gitconfig
	
	cp ./docker/.bashrc ./user/.bashrc
	cp ./docker/.vimrc ./user/.vimrc
	
	docker run --rm -it \
	--workdir=/aosp \
	--name ${DOCKER_NAME} \
	--hostname ${DOCKER_NAME} \
	--user ${UID}:${GID} \
	-v $(pwd)/user:/home/user \
	-v $(pwd)/aosp:/aosp \
	${BUILDER_TAG}
fi	 	
