#!/bin/sh

USER=$(id -un)
UID=$(id -u)
GID=$(id -g)
BUILDER_TAG=aosp-${USER}:v0.0.2
DOCKER_NAME=$(id -un)

if [ "$1" = "docker" ]
then
	docker build --build-arg uid=${UID} --build-arg gid=${GID} -t ${BUILDER_TAG} docker
elif [ "$1" = "aosp" ]
then
	docker run --rm -it \
	--workdir=/home/user/aosp \
	--name ${DOCKER_NAME} \
	--hostname ${DOCKER_NAME} \
	--user ${UID}:${GID} \
	-v ~/.gitconfig:/home/user/.gitconfig:ro \
	-v $(pwd)/aosp:/home/user/aosp \
	${BUILDER_TAG}
fi	 	
